import { generateStaffCode } from '../utils/staffCodeGenerator';

// Initial pre-loaded staff members to showcase system functionality out of the box
export const INITIAL_STAFF = [
  {
    id: 'staff-137-052-1001',
    firstName: 'Jean Claude',
    middleName: 'Munyaneza',
    lastName: 'Karekezi',
    gender: 'male',
    genderCode: '8',
    nationality: 'rwandan',
    nationalityCode: '1',
    department: 'trainer',
    departmentCode: '3',
    branch: 'kigali',
    branchCode: '1',
    educationLevel: 'master',
    educationCode: '05',
    certificateRange: '6-10',
    certificateCode: '2',
    employeeNumber: 1,
    jobTitle: 'Senior Technical Trainer',
    phone: '+250 788 123 456',
    email: 'jc.karekezi@ksp.rw',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    dateJoined: '2023-01-15',
    employmentStatus: 'active',
    emergencyContact: 'Marie Karekezi (+250 788 987 654)',
    notes: 'Certified lead instructor for drone engineering.',
    staffCode: 'KSP-138-052-1001' // 1 (Rwandan) 3 (Trainer) 8 (Male) - 05 (Masters) 2 (6-10 certs) - 1 (Kigali) 001
  },
  {
    id: 'staff-127-000-1002',
    firstName: 'Diane',
    middleName: 'Uwase',
    lastName: 'Mukamana',
    gender: 'female',
    genderCode: '7',
    nationality: 'rwandan',
    nationalityCode: '1',
    department: 'management',
    departmentCode: '2',
    branch: 'kigali',
    branchCode: '1',
    educationLevel: 'bachelor',
    educationCode: '00',
    certificateRange: '0',
    certificateCode: '0',
    employeeNumber: 2,
    jobTitle: 'HR & Operations Manager',
    phone: '+250 788 234 567',
    email: 'diane.uwase@ksp.rw',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    dateJoined: '2022-06-01',
    employmentStatus: 'active',
    emergencyContact: 'Paul Uwase (+250 788 876 543)',
    notes: 'Manages staff welfare and attendance operations.',
    staffCode: 'KSP-127-000-1002' // 1 (Rwandan) 2 (Mgmt) 7 (Female) - 00 (Bachelor) 0 (0 certs) - 1 (Kigali) 002
  },
  {
    id: 'staff-218-103-2001',
    firstName: 'Dr. Robert',
    middleName: 'John',
    lastName: 'Smith',
    gender: 'male',
    genderCode: '8',
    nationality: 'foreigner',
    nationalityCode: '2',
    department: 'executive',
    departmentCode: '1',
    branch: 'kayonza',
    branchCode: '2',
    educationLevel: 'phd',
    educationCode: '10',
    certificateRange: '11+',
    certificateCode: '3',
    employeeNumber: 1,
    jobTitle: 'Chief Academic Officer',
    phone: '+250 789 345 678',
    email: 'r.smith@ksp.rw',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    dateJoined: '2021-03-10',
    employmentStatus: 'active',
    emergencyContact: 'Sarah Smith (+1 555 019 2834)',
    notes: 'Directs curriculum strategy across all branches.',
    staffCode: 'KSP-218-103-2001' // 2 (Foreigner) 1 (Exec) 8 (Male) - 10 (PhD) 3 (11+ certs) - 2 (Kayonza) 001
  },
  {
    id: 'staff-147-011-3001',
    firstName: 'Aline',
    middleName: 'Keza',
    lastName: 'Ingabire',
    gender: 'female',
    genderCode: '7',
    nationality: 'rwandan',
    nationalityCode: '1',
    department: 'other',
    departmentCode: '4',
    branch: 'elsewhere',
    branchCode: '3',
    educationLevel: 'highschool',
    educationCode: '01',
    certificateRange: '1-5',
    certificateCode: '1',
    employeeNumber: 1,
    jobTitle: 'IT & Reception Support',
    phone: '+250 788 456 789',
    email: 'aline.ingabire@ksp.rw',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    dateJoined: '2024-02-01',
    employmentStatus: 'active',
    emergencyContact: 'Claude Ingabire (+250 788 111 222)',
    notes: 'Handles entrance desk and barcode verification.',
    staffCode: 'KSP-147-011-3001' // 1 (Rwandan) 4 (Other) 7 (Female) - 01 (A2 Highschool) 1 (1-5 certs) - 3 (Elsewhere) 001
  }
];
